[package]
name = "pnull-ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pnull-core = { path = "../pnull-core", version = "=0.0.2" }
reqwest.workspace = true
scraper.workspace = true
regex.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tempfile.workspace = true
url.workspace = true
wait-timeout.workspace = true

[lints]
workspace = true
