[package]
name = "pnull-ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
image = { version = "0.25.6", default-features = false, features = ["png"] }
pnull-core = { path = "../pnull-core", version = "=0.0.4" }
pnull-geometry = { path = "../pnull-geometry", version = "=0.0.4" }
pnull-http = { path = "../pnull-http", version = "=0.0.4" }
quick-xml.workspace = true
regex.workspace = true
reqwest.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
url.workspace = true
wait-timeout.workspace = true

[lints]
workspace = true
