//! Temporary fixture generator for the committed v0.0.2 migration fixture.
//! Creates a `SQLite` database at schema version 1 (v0.0.2) with representative
//! rows in every v0.0.2 table, then dumps it as SQL. Run with:
//!   cargo run -p pnull-core --example `gen_v02_fixture`
//! Output is written to fixtures/migration/v0.0.2-minimal.sql.

use rusqlite::{Connection, params};
use std::io::Write as _;

const V1_DDL: &str = "
CREATE TABLE evidence (
  id TEXT PRIMARY KEY,
  sha256 TEXT NOT NULL,
  source_url TEXT NOT NULL,
  record_json TEXT NOT NULL,
  extracted_text TEXT NOT NULL
);
CREATE TABLE findings (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  finding_json TEXT NOT NULL
);
CREATE TABLE alerts (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  alert_json TEXT NOT NULL
);
CREATE TABLE approvals (
  alert_id TEXT PRIMARY KEY REFERENCES alerts(id),
  draft_digest TEXT NOT NULL,
  approved_at TEXT NOT NULL
);
CREATE TABLE posts (
  alert_id TEXT PRIMARY KEY REFERENCES alerts(id),
  remote_ids_json TEXT NOT NULL,
  posted_at TEXT NOT NULL
);
CREATE TABLE source_fetches (
  source_id TEXT PRIMARY KEY,
  fetched_at_unix INTEGER NOT NULL
);
CREATE TABLE post_segments (
  alert_id TEXT NOT NULL REFERENCES posts(alert_id),
  segment_index INTEGER NOT NULL,
  remote_id TEXT NOT NULL,
  PRIMARY KEY(alert_id, segment_index)
);
CREATE TABLE matters (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL,
  official_matter_id TEXT NOT NULL,
  matter_json TEXT NOT NULL
);
CREATE TABLE matter_attachments (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL REFERENCES matters(id),
  attachment_json TEXT NOT NULL
);
CREATE TABLE subjects (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  subject_json TEXT NOT NULL
);
CREATE TABLE actions (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  action_json TEXT NOT NULL
);
CREATE TABLE text_maps (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  text_map_json TEXT NOT NULL
);
CREATE TABLE page_citations (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  page_citation_json TEXT NOT NULL
);
CREATE TABLE review_decisions (
  id TEXT PRIMARY KEY,
  citation_id TEXT NOT NULL,
  decision_json TEXT NOT NULL
);
CREATE TABLE processing_runs (
  id TEXT PRIMARY KEY,
  run_json TEXT NOT NULL
);
CREATE TABLE source_reviews (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL,
  review_json TEXT NOT NULL
);
CREATE TABLE fetch_observations (
  id TEXT PRIMARY KEY,
  source_id TEXT,
  observation_json TEXT NOT NULL
);
CREATE TABLE x_attempts (
  id TEXT PRIMARY KEY,
  alert_id TEXT NOT NULL REFERENCES alerts(id),
  attempt_json TEXT NOT NULL
);
CREATE TABLE x_reconciliations (
  id TEXT PRIMARY KEY,
  attempt_id TEXT NOT NULL REFERENCES x_attempts(id),
  reconciliation_json TEXT NOT NULL
);
CREATE TABLE publication_allowlists (
  id TEXT PRIMARY KEY,
  allowlist_json TEXT NOT NULL
);
";

fn main() {
    let dir = std::env::temp_dir().join("pnull_v02_gen");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let db_path = dir.join("pnull.db");
    let conn = Connection::open(&db_path).unwrap();
    conn.execute_batch(V1_DDL).unwrap();
    conn.pragma_update(None, "user_version", 1).unwrap();
    seed_rows(&conn);
    drop(conn);

    // Dump with sqlite3 CLI for a faithful representation.
    let output = std::process::Command::new("sqlite3")
        .arg(&db_path)
        .arg(".dump")
        .output()
        .expect("sqlite3 available");
    assert!(output.status.success(), "sqlite3 dump failed");
    let dump = String::from_utf8_lossy(&output.stdout);

    let out_path = "fixtures/migration/v0.0.2-minimal.sql";
    let mut file = std::fs::File::create(out_path).unwrap();
    let header = "-- Committed minimal v0.0.2 database fixture (schema version 1).\n\
-- Generated by crates/pnull-core/examples/gen_v02_fixture.rs. Covers every\n\
-- v0.0.2 table with representative rows. The migration test loads this and\n\
-- upgrades to v0.0.3 (version 2) proving every canonical record survives\n\
-- byte-for-byte and all v0.0.2 rows are preserved.\n";
    file.write_all(header.as_bytes()).unwrap();
    file.write_all(dump.as_bytes()).unwrap();
    // `.dump` does not preserve the user_version pragma; restore it explicitly
    // so the fixture is a faithful v0.0.2 (schema version 1) database.
    file.write_all(b"\nPRAGMA user_version = 1;\n").unwrap();
    println!("wrote {out_path} ({} bytes)", dump.len());
}

/// Inserts a representative row into every v0.0.2 (schema version 1) table.
// The function is deliberately a flat list of INSERT statements mirroring each
// table; further splitting is cosmetic churn for a dev-only generator.
#[allow(clippy::too_many_lines)]
fn seed_rows(conn: &Connection) {
    // Representative v0.0.1-style canonical row (unchanged).
    conn.execute(
        "INSERT INTO evidence(id, sha256, source_url, record_json, extracted_text) VALUES (?1,?2,?3,?4,?5)",
        params![
            "evidence:0136f043bcf653166033290ffa1522d406360e7b6345b4852af92e1739c584c3",
            "badda12921d29bf2fc2d86b274efc9544fa339db82de830ba460eaa9c6bbd2e4",
            "https://coloradosprings.legistar.com/EventDetail.aspx?ID=2654&GUID=ABC",
            "{\"kind\":\"official_api\"}",
            "Ordinance No. 25-93, Police Department Technology Surcharge."
        ],
    ).unwrap();
    conn.execute(
        "INSERT INTO findings(id, evidence_id, finding_json) VALUES (?1,?2,?3)",
        params![
            "finding:0000000000000000000000000000000000000000000000000000000000000000",
            "evidence:0136f043bcf653166033290ffa1522d406360e7b6345b4852af92e1739c584c3",
            "{\"kind\":\"finding\",\"state\":\"surveillance_technology\"}"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO alerts(id, evidence_id, alert_json) VALUES (?1,?2,?3)",
        params![
            "alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6",
            "evidence:0136f043bcf653166033290ffa1522d406360e7b6345b4852af92e1739c584c3",
            "{\"id\":\"alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6\",\"state\":\"scheduled_for_public_hearing\"}"
        ],
    ).unwrap();
    conn.execute(
        "INSERT INTO approvals(alert_id, draft_digest, approved_at) VALUES (?1,?2,?3)",
        params![
            "alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6",
            "demo-draft-digest",
            "2026-08-02T00:00:00Z"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO posts(alert_id, remote_ids_json, posted_at) VALUES (?1,?2,?3)",
        params![
            "alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6",
            "[\"segment-1\",\"segment-2\"]",
            "2026-08-02T00:00:01Z"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO source_fetches(source_id, fetched_at_unix) VALUES (?1,?2)",
        params!["colorado-springs-legistar-events", 1_754_000_000],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO post_segments(alert_id, segment_index, remote_id) VALUES (?1,?2,?3), (?1,?4,?5)",
        params!["alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6", 0, "segment-1", 1, "segment-2"],
    ).unwrap();

    // v0.0.2 supplemental rows.
    conn.execute(
        "INSERT INTO matters(id, source_id, official_matter_id, matter_json) VALUES (?1,?2,?3,?4)",
        params!["matter:co-25-93", "co", "25-93", "{\"id\":\"matter:co-25-93\",\"official_matter_id\":\"25-93\",\"title\":\"Ordinance No. 25-93\",\"status\":\"adopted\",\"document_role\":\"ordinance\"}"],
    ).unwrap();
    conn.execute(
        "INSERT INTO matter_attachments(id, matter_id, attachment_json) VALUES (?1,?2,?3)",
        params!["attachment:1", "matter:co-25-93", "{\"id\":\"attachment:1\",\"matter_id\":\"matter:co-25-93\",\"official_id\":\"att1\",\"name\":\"draft.pdf\",\"url\":\"https://example.test/draft.pdf\"}"],
    ).unwrap();
    conn.execute(
        "INSERT INTO subjects(id, matter_id, subject_json) VALUES (?1,?2,?3)",
        params!["subject:1", "matter:co-25-93", "{\"id\":\"subject:1\",\"matter_id\":\"matter:co-25-93\",\"kind\":\"surveillance_technology\",\"name\":\"Surveillance Technology\",\"known\":true}"],
    ).unwrap();
    conn.execute(
        "INSERT INTO actions(id, matter_id, subject_id, action_json) VALUES (?1,?2,?3,?4)",
        params!["action:1", "matter:co-25-93", "subject:1", "{\"id\":\"action:1\",\"matter_id\":\"matter:co-25-93\",\"subject_id\":\"subject:1\",\"kind\":\"approved\",\"summary\":\"Council approved\",\"known\":true}"],
    ).unwrap();
    conn.execute(
        "INSERT INTO processing_runs(id, run_json) VALUES (?1,?2)",
        params!["run:1", "{\"id\":\"run:1\",\"schema_version\":1,\"pnull_version\":\"0.0.2\",\"outcome\":\"complete\"}"],
    ).unwrap();
    conn.execute(
        "INSERT INTO source_reviews(id, source_id, review_json) VALUES (?1,?2,?3)",
        params![
            "sr:1",
            "co",
            "{\"id\":\"sr:1\",\"source_id\":\"co\",\"reviewer\":\"operator\",\"note\":\"approved\"}"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO fetch_observations(id, source_id, observation_json) VALUES (?1,?2,?3)",
        params![
            "fo:1",
            "co",
            "{\"id\":\"fo:1\",\"source_id\":\"co\",\"status_code\":200}"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO x_attempts(id, alert_id, attempt_json) VALUES (?1,?2,?3)",
        params![
            "xa:1",
            "alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6",
            "{\"id\":\"xa:1\",\"status\":\"posted\"}"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO x_reconciliations(id, attempt_id, reconciliation_json) VALUES (?1,?2,?3)",
        params![
            "xr:1",
            "xa:1",
            "{\"id\":\"xr:1\",\"decision\":\"confirmed\"}"
        ],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO publication_allowlists(id, allowlist_json) VALUES (?1,?2)",
        params![
            "allow:1",
            "{\"id\":\"allow:1\",\"field_categories\":[\"quote\",\"locator\"]}"
        ],
    )
    .unwrap();
}
