-- Committed minimal v0.0.2 database fixture (schema version 1).
-- Generated by crates/pnull-core/examples/gen_v02_fixture.rs. Covers every
-- v0.0.2 table with representative rows. The migration test loads this and
-- upgrades to v0.0.3 (version 2) proving every canonical record survives
-- byte-for-byte and all v0.0.2 rows are preserved.
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE evidence (
  id TEXT PRIMARY KEY,
  sha256 TEXT NOT NULL,
  source_url TEXT NOT NULL,
  record_json TEXT NOT NULL,
  extracted_text TEXT NOT NULL
);
INSERT INTO evidence VALUES('evidence:0136f043bcf653166033290ffa1522d406360e7b6345b4852af92e1739c584c3','badda12921d29bf2fc2d86b274efc9544fa339db82de830ba460eaa9c6bbd2e4','https://coloradosprings.legistar.com/EventDetail.aspx?ID=2654&GUID=ABC','{"kind":"official_api"}','Ordinance No. 25-93, Police Department Technology Surcharge.');
CREATE TABLE findings (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  finding_json TEXT NOT NULL
);
INSERT INTO findings VALUES('finding:0000000000000000000000000000000000000000000000000000000000000000','evidence:0136f043bcf653166033290ffa1522d406360e7b6345b4852af92e1739c584c3','{"kind":"finding","state":"surveillance_technology"}');
CREATE TABLE alerts (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  alert_json TEXT NOT NULL
);
INSERT INTO alerts VALUES('alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6','evidence:0136f043bcf653166033290ffa1522d406360e7b6345b4852af92e1739c584c3','{"id":"alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6","state":"scheduled_for_public_hearing"}');
CREATE TABLE approvals (
  alert_id TEXT PRIMARY KEY REFERENCES alerts(id),
  draft_digest TEXT NOT NULL,
  approved_at TEXT NOT NULL
);
INSERT INTO approvals VALUES('alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6','demo-draft-digest','2026-08-02T00:00:00Z');
CREATE TABLE posts (
  alert_id TEXT PRIMARY KEY REFERENCES alerts(id),
  remote_ids_json TEXT NOT NULL,
  posted_at TEXT NOT NULL
);
INSERT INTO posts VALUES('alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6','["segment-1","segment-2"]','2026-08-02T00:00:01Z');
CREATE TABLE source_fetches (
  source_id TEXT PRIMARY KEY,
  fetched_at_unix INTEGER NOT NULL
);
INSERT INTO source_fetches VALUES('colorado-springs-legistar-events',1754000000);
CREATE TABLE post_segments (
  alert_id TEXT NOT NULL REFERENCES posts(alert_id),
  segment_index INTEGER NOT NULL,
  remote_id TEXT NOT NULL,
  PRIMARY KEY(alert_id, segment_index)
);
INSERT INTO post_segments VALUES('alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6',0,'segment-1');
INSERT INTO post_segments VALUES('alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6',1,'segment-2');
CREATE TABLE matters (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL,
  official_matter_id TEXT NOT NULL,
  matter_json TEXT NOT NULL
);
INSERT INTO matters VALUES('matter:co-25-93','co','25-93','{"id":"matter:co-25-93","official_matter_id":"25-93","title":"Ordinance No. 25-93","status":"adopted","document_role":"ordinance"}');
CREATE TABLE matter_attachments (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL REFERENCES matters(id),
  attachment_json TEXT NOT NULL
);
INSERT INTO matter_attachments VALUES('attachment:1','matter:co-25-93','{"id":"attachment:1","matter_id":"matter:co-25-93","official_id":"att1","name":"draft.pdf","url":"https://example.test/draft.pdf"}');
CREATE TABLE subjects (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  subject_json TEXT NOT NULL
);
INSERT INTO subjects VALUES('subject:1','matter:co-25-93','{"id":"subject:1","matter_id":"matter:co-25-93","kind":"surveillance_technology","name":"Surveillance Technology","known":true}');
CREATE TABLE actions (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  action_json TEXT NOT NULL
);
INSERT INTO actions VALUES('action:1','matter:co-25-93','subject:1','{"id":"action:1","matter_id":"matter:co-25-93","subject_id":"subject:1","kind":"approved","summary":"Council approved","known":true}');
CREATE TABLE text_maps (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  text_map_json TEXT NOT NULL
);
CREATE TABLE page_citations (
  id TEXT PRIMARY KEY,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  page_citation_json TEXT NOT NULL
);
CREATE TABLE review_decisions (
  id TEXT PRIMARY KEY,
  citation_id TEXT NOT NULL,
  decision_json TEXT NOT NULL
);
CREATE TABLE processing_runs (
  id TEXT PRIMARY KEY,
  run_json TEXT NOT NULL
);
INSERT INTO processing_runs VALUES('run:1','{"id":"run:1","schema_version":1,"pnull_version":"0.0.2","outcome":"complete"}');
CREATE TABLE source_reviews (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL,
  review_json TEXT NOT NULL
);
INSERT INTO source_reviews VALUES('sr:1','co','{"id":"sr:1","source_id":"co","reviewer":"operator","note":"approved"}');
CREATE TABLE fetch_observations (
  id TEXT PRIMARY KEY,
  source_id TEXT,
  observation_json TEXT NOT NULL
);
INSERT INTO fetch_observations VALUES('fo:1','co','{"id":"fo:1","source_id":"co","status_code":200}');
CREATE TABLE x_attempts (
  id TEXT PRIMARY KEY,
  alert_id TEXT NOT NULL REFERENCES alerts(id),
  attempt_json TEXT NOT NULL
);
INSERT INTO x_attempts VALUES('xa:1','alert:94c9526803b6e122e8b4f31a05f21fe84535b948812d253d2817bc9f6a71b2c6','{"id":"xa:1","status":"posted"}');
CREATE TABLE x_reconciliations (
  id TEXT PRIMARY KEY,
  attempt_id TEXT NOT NULL REFERENCES x_attempts(id),
  reconciliation_json TEXT NOT NULL
);
INSERT INTO x_reconciliations VALUES('xr:1','xa:1','{"id":"xr:1","decision":"confirmed"}');
CREATE TABLE publication_allowlists (
  id TEXT PRIMARY KEY,
  allowlist_json TEXT NOT NULL
);
INSERT INTO publication_allowlists VALUES('allow:1','{"id":"allow:1","field_categories":["quote","locator"]}');
COMMIT;

PRAGMA user_version = 1;
